apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2020-09-06T17:46:58Z"
  name: kube-developer-scheduler
  namespace: kube-system
  resourceVersion: "1123993"
  selfLink: /apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-developer-scheduler
  uid: 6da620fd-f11d-49a7-89fd-b162abe50fbc
spec:
  acquireTime: "2020-09-06T17:46:58.000000Z"
  holderIdentity: minikube_30738b37-9b0d-436c-a91e-87fefdb16611
  leaseDurationSeconds: 15
  leaseTransitions: 0
  renewTime: "2020-09-20T06:10:12.914360Z"
